name: clang-format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  changes:
    runs-on:  [ self-hosted, small ]
    outputs:
      source_code: ${{ steps.filter.outputs.source_code }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            source_code:
              - 'bolt/**'
              - '!bolt/**/*.md'
  format-check:
    needs: changes
    if: ${{ needs.changes.outputs.source_code == 'true' }}
    runs-on: [ self-hosted, small ]
    container: bolt-registry:5000/bolt-ci:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: clang-format check
      run: |
        make clang-format-check
